import { NextResponse } from 'next/server';

export async function POST(request: Request) {
  // Simulate AI processing delay
  await new Promise(resolve => setTimeout(resolve, 3000));

  // Mock feedback data
  // In a real app, this would be generated by an LLM analyzing the image
  const feedback = {
    score: 85,
    summary: "Strong visual hierarchy and good use of the grid system. However, the call-to-action details could be more prominent.",
    criteria: [
      { name: "Contrast Ratio", status: "pass", score: 90, comment: "Excellent contrast throughout (AA/AAA compliant)." },
      { name: "Typography", status: "pass", score: 88, comment: "Font scaling is consistent and readable." },
      { name: "Spacing & Layout", status: "pass", score: 85, comment: "Good use of white space, though the footer feels cramped." },
      { name: "Visual Hierarchy", status: "pass", score: 92, comment: "Clear path for the user's eye to follow." },
      { name: "Accessibility", status: "warning", score: 70, comment: "Some button labels are missing aria-labels." }
    ]
  };

  return NextResponse.json(feedback);
}
